include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "build/**"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    public_member_api_docs: false
    sized_box_for_whitespace: false
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    sort_pub_dependencies: true
