name: Quiz_Guru
description: App where you can check your knowledge on Android

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # helpers 
  basic_utils: ^1.2.0
  email_validator: ^1.0.0
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  equatable: ^1.2.5
  optional: ^5.0.0

  # firebase
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  firebase_database: ^4.0.0
  firebase_messaging: ^7.0.3
  google_sign_in: ^4.5.3

  # ui
  flip_card: ^0.4.4
  grouped_buttons: ^1.0.4
  flutter_feather_icons: ^1.0.3
  flutter_svg: ^0.18.0
  syncfusion_flutter_gauges: ^18.2.55

  # core
  flutter_bloc: ^6.0.5
  hydrated_bloc: ^6.0.1
  get_it: ^5.0.1
  shared_preferences: ^0.5.12
  timezone: ^0.5.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  import_sorter: ^4.4.1

flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true
#  build_runner:
#  json_serializable: ^3.5.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lang/en.json
    - lang/ru.json
    - assets/images/
    - assets/images/doodles/
    - assets/images/icons/
    
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 900
